### ISSUE TITLE
Transmit/Receive types should include Transport controls

### ISSUE THREAD

**Issue by eokuwwy** [eokuwwy/open-midi-rtc-schema#11]
- START
- STOP
- CONTINUE

**Comment by designerfuzzi** [comment]
- **SPP**, Song Position Pointer (if not already supported)
  - some devices allow receiving SPP while playing 
  - some only allow while clock is not running (midi spec variant)
- **MMC** Midi Machine Control commands, could be seen as sysex
  - which look like (`F0 7F DEVICEID (06|07) mc F7`), where `DEVICEID` is usually 7F and `mc` is the command, so
  - (`F0 7F 7F (06|07) mc F7`), **STOP**, mc=01,
  - (`F0 7F 7F (06|07) mc F7`), **START**, mc=02,
  - (`F0 7F 7F (06|07) mc F7`), **RECORD**, mc=06,
  - (`F0 7F 7F (06|07) mc F7`), **SEEK FAST FORWARD**, mc=04
  - (`F0 7F 7F (06|07) mc F7`), **SEEK REWIND**, mc=05
  - and others 
    - 03 Deferred Play (play after no longer busy)
       07 Record Exit (AKA [[Punch out (music)|Punch out]])
       08 Record Pause
       09 Pause (pause playback)
       0A Eject (disengage media container from MMC device)
       0B Chase
       0D MMC Reset (to default/startup state)
       40 Write (AKA Record Ready, AKA Arm Tracks)
       44 Goto (AKA Locate)
       47 Shuttle

and there is
- **ACTIVE SENS**, `0xFE` a command that is send in between the next 300ms after idle to signal the machine is still up.
some devices shut down their runloop to analyse midi data when active sens is not send after machine/clock stop. While this looks very special, it is actually very useful specially with network midi where sockets need to stay open or otherwise shut down
