### ISSUE TITLE
Support for CCs that use MSB and LSB (14-bit)

### ISSUE THREAD

**Issue by eokuwwy** [eokuwwy/open-midi-rtc-schema#8]
Right now the schema treats all CC's as 7-bit. Some devices use 14-bits for CCs.

**Comment by designerfuzzi** [comment]
Not sure if CCs that use 14bit instead of 7bit msgs for plain CC signals are really following the midi spec 1.0. It may just be a convenient way to support RPN msgs with the very same analytics loop on that particular endpoint/device. 
Because 14bit msgs with MSB and LSB are clearly to be understood as RPN/NRPN. 

Why i point at this? Because...
How would a midi packet analyser distinguish between 14bit CC and 14 bit RPN/NRPN when they look just the same?
